# Generated by Django 5.1.5 on 2025-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
