# Generated by Django 5.1.5 on 2025-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingJoke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joke', models.CharField(max_length=1000)),
                ('punchline', models.CharField(max_length=1000)),
            ],
        ),
    ]
